feat: Implement -vt flag
- With given theme name, it will check only that theme dir
- With no given name, all themes in input-dir will be checked

diff --git a/app/mytm b/app/mytm
--- a/app/mytm
+++ b/app/mytm
@@ -17,6 +17,8 @@ fi
 INPUT_DIR="$PROJECT_ROOT/themes"
 OUTPUT_DIR="$PROJECT_ROOT/dist"
 CONFIG_FILE="$PROJECT_ROOT/config.yml"
+VALIDATE_ONLY=false
+VALIDATE_THEME=""
 TEMP_DIR="$PROJECT_ROOT/.tmp"
 HASH_ALGO="sha256"
 MAX_ARCHIVE_VERSIONS=10
@@ -44,13 +46,16 @@ DESC:
 
 USAGE:
     $0 [OPTIONS]
+    $0 -vt <theme_name> [-i <input_dir>]
 
 FLAGS:
-    -h, --help                Show this help message
-    -i, --input-dir DIR       Override input directory from config
-    -o, --output-dir DIR      Override output directory from config
-    -c, --config FILE         Set config file (default: $CONFIG_FILE)
-    -rt,--repo-template FILE  Set README template file (default: $README_TEMPLATE)
+    -h,  --help                Show this help message
+    -i,  --input-dir DIR       Override input directory from config
+    -o,  --output-dir DIR      Override output directory from config
+    -c,  --config FILE         Set config file (default: $CONFIG_FILE)
+    -vt, --validate-theme      Validate given/all theme dirs (inside input-dir)
+
+EXAMPLE
 EOF
 }
 
@@ -94,6 +99,15 @@ while [[ $# -gt 0 ]]; do
   -c | --config)
     CONFIG_FILE="$2"
     shift 2
+    ;;
+   -vt|--validate-theme)
+    VALIDATE_ONLY=true
+    if [[ -n "$2" && "$2" != -* ]]; then
+      VALIDATE_THEME="$2"
+      shift 2
+    else
+      shift 1
+    fi
     ;;
   *)
     log.error "Unknown option: $1"
@@ -146,6 +160,49 @@ else
 fi
 
 
+#------------- Only validation check -------------
+
+if [ "$VALIDATE_ONLY" == "true" ]; then
+
+    log.tab.reset
+    log.success -b "Environment setup complete\n"
+
+    log.info -b "Starting Validation..."
+    log.tab.inc
+
+    validation_failed=0
+
+    if [[ -n "$VALIDATE_THEME" ]]; then
+        log.info "Validating theme: $VALIDATE_THEME"
+        log.tab.inc
+        if ! validate-theme-dir "$INPUT_DIR/$VALIDATE_THEME"; then
+            validation_failed=1
+        fi
+        log.tab.dec
+    else
+        for theme_dir in "$INPUT_DIR"/*; do
+            theme_name="$(basename "$theme_dir")"
+            log.info -b "Validating theme: $theme_name"
+
+            log.tab.inc
+            if ! validate-theme-dir "$theme_dir"; then
+                validation_failed=1
+            fi
+            log.tab.dec
+            echo
+        done
+    fi
+
+    log.tab.reset
+
+    if [ "$validation_failed" -eq 1 ]; then
+        log.error -b "Validation failed. Please fix the errors above."
+        exit 1
+    else
+        log.success -b "${GREEN}Validation complete, Everything seems good.${NC}"
+        exit 0
+    fi
+fi
 
 
 # ------------ Index.json check ------------
